import React,{useMemo,useState} from "react";import{createRoot}from"react-dom/client";import{Instagram,Linkedin,ChevronLeft,ChevronRight,Check,Plus,CalendarDays,ClipboardList,Bell,Layers3,Settings2}from"lucide-react";import"./styles.css";

type Channel="instagram"|"linkedin"; type Item={name:string;channel:Channel;coverage?:string};
const schedule:Record<number,Item[]>={
1:[{name:"Post 3000",channel:"linkedin",coverage:"2026-10-26"},{name:"Corte Pazy by Pazy",channel:"instagram",coverage:"2026-10-09"},{name:"Carrossel",channel:"instagram",coverage:"2026-10-26"},{name:"Frase",channel:"instagram",coverage:"2026-10-28"},{name:"Story Cartinha",channel:"instagram",coverage:"2026-11-06"}],
2:[{name:"Artigo",channel:"linkedin"},{name:"Corte Pazy by Pazy",channel:"instagram",coverage:"2026-10-09"},{name:"Story Artigo com Link",channel:"instagram"},{name:"Carrossel Artigo",channel:"instagram"},{name:"Story Cartinha",channel:"instagram",coverage:"2026-11-06"}],
3:[{name:"Post TI",channel:"linkedin",coverage:"2026-10-28"},{name:"Corte Pazy by Pazy",channel:"instagram",coverage:"2026-10-09"},{name:"Frase",channel:"instagram",coverage:"2026-10-28"},{name:"Story Cartinha",channel:"instagram",coverage:"2026-11-06"}],
4:[{name:"Vídeo Curto Podcast",channel:"linkedin"},{name:"Story Podcast",channel:"instagram"},{name:"Corte Podcast",channel:"instagram"},{name:"Story Cartinha",channel:"instagram",coverage:"2026-11-06"}],
5:[{name:"Carrossel LinkedIn",channel:"linkedin",coverage:"2026-10-30"},{name:"Story Pazy by Pazy",channel:"instagram",coverage:"2026-10-09"},{name:"Corte Pazy by Pazy",channel:"instagram",coverage:"2026-10-09"},{name:"Story Cartinha",channel:"instagram",coverage:"2026-11-06"}],
6:[{name:"Story Cartinha",channel:"instagram",coverage:"2026-11-06"}],0:[{name:"Story Cartinha",channel:"instagram",coverage:"2026-11-06"}]};
const days=["DOM","SEG","TER","QUA","QUI","SEX","SÁB"];const iso=(d:Date)=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`};const startWeek=(d:Date)=>{const x=new Date(d);x.setHours(12,0,0,0);const day=x.getDay();x.setDate(x.getDate()-(day===0?6:day-1));return x};
function App(){const [anchor,setAnchor]=useState(new Date(2026,9,7,12));const [manual,setManual]=useState<Record<string,boolean>>({});const start=startWeek(anchor);const week=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d}),[start.getTime()]);const all=week.flatMap(d=>(schedule[d.getDay()]||[]).map(x=>({d,x,key:iso(d)+"-"+x.name})));const done=all.filter(({d,x,key})=>manual[key]||!!x.coverage&&iso(d)<=x.coverage).length;const pct=Math.round(done/all.length*100);
return <div className="app"><aside><div className="brand">PAZY<span>content</span></div><nav><b><CalendarDays/>Minha semana</b><span><ClipboardList/>Pendências</span><span><Layers3/>Conteúdos base</span><span><Bell/>Avisos</span><span><Settings2/>Organograma</span></nav><button className="add"><Plus/>Nova tarefa</button></aside><main><header><div><small>CALENDÁRIO DE CONTEÚDO</small><h1>Minha semana</h1></div><div className="nav"><button onClick={()=>{const d=new Date(anchor);d.setDate(d.getDate()-7);setAnchor(d)}}><ChevronLeft/></button><button onClick={()=>setAnchor(new Date(2026,9,7,12))}>Hoje</button><button onClick={()=>{const d=new Date(anchor);d.setDate(d.getDate()+7);setAnchor(d)}}><ChevronRight/></button></div></header><section className="weektitle"><strong>{start.toLocaleDateString("pt-BR",{day:"2-digit",month:"short"})} — {week[6].toLocaleDateString("pt-BR",{day:"2-digit",month:"short",year:"numeric"})}</strong><span>{done}/{all.length} resolvidos · {pct}%</span><div className="bar"><i style={{width:pct+"%"}}/></div></section><section className="grid">{week.map(d=><div className={"day "+(iso(d)==="2026-10-07"?"today":"")} key={iso(d)}><div className="dayhead"><b>{days[d.getDay()]}</b><em>{String(d.getDate()).padStart(2,"0")}</em></div><div className="cards">{(schedule[d.getDay()]||[]).map(x=>{const key=iso(d)+"-"+x.name;const auto=!!x.coverage&&iso(d)<=x.coverage;const checked=auto||manual[key];const Icon=x.channel==="instagram"?Instagram:Linkedin;return <button className={"card "+(checked?"checked":"")} key={key} onClick={()=>!auto&&setManual(v=>({...v,[key]:!v[key]}))} title={auto?"Programado automaticamente":"Clique para concluir"}><Icon className="media"/><span>{x.name}</span><i>{checked?<Check/>:<span/>}</i></button>})}</div></div>)}</section></main></div>}
createRoot(document.getElementById("root")!).render(<App/>);